// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	context "context"

	elasticache "github.com/aws/aws-sdk-go-v2/service/elasticache"
	mock "github.com/stretchr/testify/mock"
)

// ElastiCacheClient is an autogenerated mock type for the ElastiCacheClient type
type ElastiCacheClient struct {
	mock.Mock
}

type ElastiCacheClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ElastiCacheClient) EXPECT() *ElastiCacheClient_Expecter {
	return &ElastiCacheClient_Expecter{mock: &_m.Mock}
}

// DescribeCacheClusters provides a mock function with given fields: ctx, params, optFns
func (_m *ElastiCacheClient) DescribeCacheClusters(ctx context.Context, params *elasticache.DescribeCacheClustersInput, optFns ...func(*elasticache.Options)) (*elasticache.DescribeCacheClustersOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *elasticache.DescribeCacheClustersOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *elasticache.DescribeCacheClustersInput, ...func(*elasticache.Options)) (*elasticache.DescribeCacheClustersOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *elasticache.DescribeCacheClustersInput, ...func(*elasticache.Options)) *elasticache.DescribeCacheClustersOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*elasticache.DescribeCacheClustersOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *elasticache.DescribeCacheClustersInput, ...func(*elasticache.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ElastiCacheClient_DescribeCacheClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeCacheClusters'
type ElastiCacheClient_DescribeCacheClusters_Call struct {
	*mock.Call
}

// DescribeCacheClusters is a helper method to define mock.On call
//   - ctx context.Context
//   - params *elasticache.DescribeCacheClustersInput
//   - optFns ...func(*elasticache.Options)
func (_e *ElastiCacheClient_Expecter) DescribeCacheClusters(ctx interface{}, params interface{}, optFns ...interface{}) *ElastiCacheClient_DescribeCacheClusters_Call {
	return &ElastiCacheClient_DescribeCacheClusters_Call{Call: _e.mock.On("DescribeCacheClusters",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *ElastiCacheClient_DescribeCacheClusters_Call) Run(run func(ctx context.Context, params *elasticache.DescribeCacheClustersInput, optFns ...func(*elasticache.Options))) *ElastiCacheClient_DescribeCacheClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*elasticache.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*elasticache.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*elasticache.DescribeCacheClustersInput), variadicArgs...)
	})
	return _c
}

func (_c *ElastiCacheClient_DescribeCacheClusters_Call) Return(_a0 *elasticache.DescribeCacheClustersOutput, _a1 error) *ElastiCacheClient_DescribeCacheClusters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ElastiCacheClient_DescribeCacheClusters_Call) RunAndReturn(run func(context.Context, *elasticache.DescribeCacheClustersInput, ...func(*elasticache.Options)) (*elasticache.DescribeCacheClustersOutput, error)) *ElastiCacheClient_DescribeCacheClusters_Call {
	_c.Call.Return(run)
	return _c
}

// NewElastiCacheClient creates a new instance of ElastiCacheClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElastiCacheClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElastiCacheClient {
	mock := &ElastiCacheClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
