// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ConfigStore is an autogenerated mock type for the ConfigStore type
type ConfigStore struct {
	mock.Mock
}

type ConfigStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigStore) EXPECT() *ConfigStore_Expecter {
	return &ConfigStore_Expecter{mock: &_m.Mock}
}

// GetConfigValue provides a mock function with given fields: ctx, key
func (_m *ConfigStore) GetConfigValue(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigStore_GetConfigValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigValue'
type ConfigStore_GetConfigValue_Call struct {
	*mock.Call
}

// GetConfigValue is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *ConfigStore_Expecter) GetConfigValue(ctx interface{}, key interface{}) *ConfigStore_GetConfigValue_Call {
	return &ConfigStore_GetConfigValue_Call{Call: _e.mock.On("GetConfigValue", ctx, key)}
}

func (_c *ConfigStore_GetConfigValue_Call) Run(run func(ctx context.Context, key string)) *ConfigStore_GetConfigValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ConfigStore_GetConfigValue_Call) Return(_a0 string, _a1 error) *ConfigStore_GetConfigValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConfigStore_GetConfigValue_Call) RunAndReturn(run func(context.Context, string) (string, error)) *ConfigStore_GetConfigValue_Call {
	_c.Call.Return(run)
	return _c
}

// NewConfigStore creates a new instance of ConfigStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigStore {
	mock := &ConfigStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
