// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	funcie "github.com/Kapps/funcie/pkg/funcie"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

type Handler_Expecter struct {
	mock *mock.Mock
}

func (_m *Handler) EXPECT() *Handler_Expecter {
	return &Handler_Expecter{mock: &_m.Mock}
}

// ForwardRequest provides a mock function with given fields: ctx, request
func (_m *Handler) ForwardRequest(ctx context.Context, request *funcie.Message) (*funcie.Response, error) {
	ret := _m.Called(ctx, request)

	var r0 *funcie.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *funcie.Message) (*funcie.Response, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *funcie.Message) *funcie.Response); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*funcie.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *funcie.Message) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Handler_ForwardRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForwardRequest'
type Handler_ForwardRequest_Call struct {
	*mock.Call
}

// ForwardRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - request *funcie.Message
func (_e *Handler_Expecter) ForwardRequest(ctx interface{}, request interface{}) *Handler_ForwardRequest_Call {
	return &Handler_ForwardRequest_Call{Call: _e.mock.On("ForwardRequest", ctx, request)}
}

func (_c *Handler_ForwardRequest_Call) Run(run func(ctx context.Context, request *funcie.Message)) *Handler_ForwardRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*funcie.Message))
	})
	return _c
}

func (_c *Handler_ForwardRequest_Call) Return(_a0 *funcie.Response, _a1 error) *Handler_ForwardRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Handler_ForwardRequest_Call) RunAndReturn(run func(context.Context, *funcie.Message) (*funcie.Response, error)) *Handler_ForwardRequest_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, application
func (_m *Handler) Register(ctx context.Context, application *funcie.Application) error {
	ret := _m.Called(ctx, application)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *funcie.Application) error); ok {
		r0 = rf(ctx, application)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Handler_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Handler_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - application *funcie.Application
func (_e *Handler_Expecter) Register(ctx interface{}, application interface{}) *Handler_Register_Call {
	return &Handler_Register_Call{Call: _e.mock.On("Register", ctx, application)}
}

func (_c *Handler_Register_Call) Run(run func(ctx context.Context, application *funcie.Application)) *Handler_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*funcie.Application))
	})
	return _c
}

func (_c *Handler_Register_Call) Return(_a0 error) *Handler_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Handler_Register_Call) RunAndReturn(run func(context.Context, *funcie.Application) error) *Handler_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Unregister provides a mock function with given fields: ctx, applicationName
func (_m *Handler) Unregister(ctx context.Context, applicationName string) error {
	ret := _m.Called(ctx, applicationName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, applicationName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Handler_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type Handler_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - ctx context.Context
//   - applicationName string
func (_e *Handler_Expecter) Unregister(ctx interface{}, applicationName interface{}) *Handler_Unregister_Call {
	return &Handler_Unregister_Call{Call: _e.mock.On("Unregister", ctx, applicationName)}
}

func (_c *Handler_Unregister_Call) Run(run func(ctx context.Context, applicationName string)) *Handler_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Handler_Unregister_Call) Return(_a0 error) *Handler_Unregister_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Handler_Unregister_Call) RunAndReturn(run func(context.Context, string) error) *Handler_Unregister_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHandler(t mockConstructorTestingTNewHandler) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
