// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Host is an autogenerated mock type for the Host type
type Host struct {
	mock.Mock
}

type Host_Expecter struct {
	mock *mock.Mock
}

func (_m *Host) EXPECT() *Host_Expecter {
	return &Host_Expecter{mock: &_m.Mock}
}

// Listen provides a mock function with given fields:
func (_m *Host) Listen() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Host_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type Host_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
func (_e *Host_Expecter) Listen() *Host_Listen_Call {
	return &Host_Listen_Call{Call: _e.mock.On("Listen")}
}

func (_c *Host_Listen_Call) Run(run func()) *Host_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Host_Listen_Call) Return(_a0 error) *Host_Listen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Host_Listen_Call) RunAndReturn(run func() error) *Host_Listen_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewHost interface {
	mock.TestingT
	Cleanup(func())
}

// NewHost creates a new instance of Host. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHost(t mockConstructorTestingTNewHost) *Host {
	mock := &Host{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
