// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HostTranslator is an autogenerated mock type for the HostTranslator type
type HostTranslator struct {
	mock.Mock
}

type HostTranslator_Expecter struct {
	mock *mock.Mock
}

func (_m *HostTranslator) EXPECT() *HostTranslator_Expecter {
	return &HostTranslator_Expecter{mock: &_m.Mock}
}

// IsHostTranslationRequired provides a mock function with given fields:
func (_m *HostTranslator) IsHostTranslationRequired() (bool, error) {
	ret := _m.Called()

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HostTranslator_IsHostTranslationRequired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHostTranslationRequired'
type HostTranslator_IsHostTranslationRequired_Call struct {
	*mock.Call
}

// IsHostTranslationRequired is a helper method to define mock.On call
func (_e *HostTranslator_Expecter) IsHostTranslationRequired() *HostTranslator_IsHostTranslationRequired_Call {
	return &HostTranslator_IsHostTranslationRequired_Call{Call: _e.mock.On("IsHostTranslationRequired")}
}

func (_c *HostTranslator_IsHostTranslationRequired_Call) Run(run func()) *HostTranslator_IsHostTranslationRequired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HostTranslator_IsHostTranslationRequired_Call) Return(_a0 bool, _a1 error) *HostTranslator_IsHostTranslationRequired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HostTranslator_IsHostTranslationRequired_Call) RunAndReturn(run func() (bool, error)) *HostTranslator_IsHostTranslationRequired_Call {
	_c.Call.Return(run)
	return _c
}

// TranslateLocalHostToResolvedHost provides a mock function with given fields: host
func (_m *HostTranslator) TranslateLocalHostToResolvedHost(host string) (string, error) {
	ret := _m.Called(host)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(host)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(host)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(host)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HostTranslator_TranslateLocalHostToResolvedHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranslateLocalHostToResolvedHost'
type HostTranslator_TranslateLocalHostToResolvedHost_Call struct {
	*mock.Call
}

// TranslateLocalHostToResolvedHost is a helper method to define mock.On call
//   - host string
func (_e *HostTranslator_Expecter) TranslateLocalHostToResolvedHost(host interface{}) *HostTranslator_TranslateLocalHostToResolvedHost_Call {
	return &HostTranslator_TranslateLocalHostToResolvedHost_Call{Call: _e.mock.On("TranslateLocalHostToResolvedHost", host)}
}

func (_c *HostTranslator_TranslateLocalHostToResolvedHost_Call) Run(run func(host string)) *HostTranslator_TranslateLocalHostToResolvedHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *HostTranslator_TranslateLocalHostToResolvedHost_Call) Return(_a0 string, _a1 error) *HostTranslator_TranslateLocalHostToResolvedHost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HostTranslator_TranslateLocalHostToResolvedHost_Call) RunAndReturn(run func(string) (string, error)) *HostTranslator_TranslateLocalHostToResolvedHost_Call {
	_c.Call.Return(run)
	return _c
}

// NewHostTranslator creates a new instance of HostTranslator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHostTranslator(t interface {
	mock.TestingT
	Cleanup(func())
}) *HostTranslator {
	mock := &HostTranslator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
