// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FunctionProxy is an autogenerated mock type for the FunctionProxy type
type FunctionProxy struct {
	mock.Mock
}

type FunctionProxy_Expecter struct {
	mock *mock.Mock
}

func (_m *FunctionProxy) EXPECT() *FunctionProxy_Expecter {
	return &FunctionProxy_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with given fields:
func (_m *FunctionProxy) Start() {
	_m.Called()
}

// FunctionProxy_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type FunctionProxy_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *FunctionProxy_Expecter) Start() *FunctionProxy_Start_Call {
	return &FunctionProxy_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *FunctionProxy_Start_Call) Run(run func()) *FunctionProxy_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FunctionProxy_Start_Call) Return() *FunctionProxy_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *FunctionProxy_Start_Call) RunAndReturn(run func()) *FunctionProxy_Start_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewFunctionProxy interface {
	mock.TestingT
	Cleanup(func())
}

// NewFunctionProxy creates a new instance of FunctionProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFunctionProxy(t mockConstructorTestingTNewFunctionProxy) *FunctionProxy {
	mock := &FunctionProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
