// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Tunnel is an autogenerated mock type for the Tunnel type
type Tunnel struct {
	mock.Mock
}

type Tunnel_Expecter struct {
	mock *mock.Mock
}

func (_m *Tunnel) EXPECT() *Tunnel_Expecter {
	return &Tunnel_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with given fields:
func (_m *Tunnel) Start() {
	_m.Called()
}

// Tunnel_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Tunnel_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *Tunnel_Expecter) Start() *Tunnel_Start_Call {
	return &Tunnel_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *Tunnel_Start_Call) Run(run func()) *Tunnel_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tunnel_Start_Call) Return() *Tunnel_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *Tunnel_Start_Call) RunAndReturn(run func()) *Tunnel_Start_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewTunnel interface {
	mock.TestingT
	Cleanup(func())
}

// NewTunnel creates a new instance of Tunnel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTunnel(t mockConstructorTestingTNewTunnel) *Tunnel {
	mock := &Tunnel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
