// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	context "context"

	websocket "github.com/Kapps/funcie/pkg/funcie/transports/websocket"
	mock "github.com/stretchr/testify/mock"
)

// Dialer is an autogenerated mock type for the Dialer type
type Dialer struct {
	mock.Mock
}

type Dialer_Expecter struct {
	mock *mock.Mock
}

func (_m *Dialer) EXPECT() *Dialer_Expecter {
	return &Dialer_Expecter{mock: &_m.Mock}
}

// Dial provides a mock function with given fields: ctx, url
func (_m *Dialer) Dial(ctx context.Context, url string) (websocket.Connection, error) {
	ret := _m.Called(ctx, url)

	var r0 websocket.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (websocket.Connection, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) websocket.Connection); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(websocket.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Dialer_Dial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dial'
type Dialer_Dial_Call struct {
	*mock.Call
}

// Dial is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *Dialer_Expecter) Dial(ctx interface{}, url interface{}) *Dialer_Dial_Call {
	return &Dialer_Dial_Call{Call: _e.mock.On("Dial", ctx, url)}
}

func (_c *Dialer_Dial_Call) Run(run func(ctx context.Context, url string)) *Dialer_Dial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Dialer_Dial_Call) Return(_a0 websocket.Connection, _a1 error) *Dialer_Dial_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Dialer_Dial_Call) RunAndReturn(run func(context.Context, string) (websocket.Connection, error)) *Dialer_Dial_Call {
	_c.Call.Return(run)
	return _c
}

// NewDialer creates a new instance of Dialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDialer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dialer {
	mock := &Dialer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
