// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Closable is an autogenerated mock type for the Closable type
type Closable struct {
	mock.Mock
}

type Closable_Expecter struct {
	mock *mock.Mock
}

func (_m *Closable) EXPECT() *Closable_Expecter {
	return &Closable_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *Closable) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Closable_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Closable_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Closable_Expecter) Close() *Closable_Close_Call {
	return &Closable_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Closable_Close_Call) Run(run func()) *Closable_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Closable_Close_Call) Return(_a0 error) *Closable_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Closable_Close_Call) RunAndReturn(run func() error) *Closable_Close_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewClosable interface {
	mock.TestingT
	Cleanup(func())
}

// NewClosable creates a new instance of Closable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClosable(t mockConstructorTestingTNewClosable) *Closable {
	mock := &Closable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
