// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	redis "github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// PubSub is an autogenerated mock type for the PubSub type
type PubSub struct {
	mock.Mock
}

type PubSub_Expecter struct {
	mock *mock.Mock
}

func (_m *PubSub) EXPECT() *PubSub_Expecter {
	return &PubSub_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function with given fields: opts
func (_m *PubSub) Channel(opts ...redis.ChannelOption) <-chan *redis.Message {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 <-chan *redis.Message
	if rf, ok := ret.Get(0).(func(...redis.ChannelOption) <-chan *redis.Message); ok {
		r0 = rf(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *redis.Message)
		}
	}

	return r0
}

// PubSub_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type PubSub_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
//   - opts ...redis.ChannelOption
func (_e *PubSub_Expecter) Channel(opts ...interface{}) *PubSub_Channel_Call {
	return &PubSub_Channel_Call{Call: _e.mock.On("Channel",
		append([]interface{}{}, opts...)...)}
}

func (_c *PubSub_Channel_Call) Run(run func(opts ...redis.ChannelOption)) *PubSub_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]redis.ChannelOption, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(redis.ChannelOption)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *PubSub_Channel_Call) Return(_a0 <-chan *redis.Message) *PubSub_Channel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PubSub_Channel_Call) RunAndReturn(run func(...redis.ChannelOption) <-chan *redis.Message) *PubSub_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields:
func (_m *PubSub) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PubSub_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type PubSub_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *PubSub_Expecter) Close() *PubSub_Close_Call {
	return &PubSub_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *PubSub_Close_Call) Run(run func()) *PubSub_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PubSub_Close_Call) Return(_a0 error) *PubSub_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PubSub_Close_Call) RunAndReturn(run func() error) *PubSub_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function with given fields: ctx
func (_m *PubSub) Receive(ctx context.Context) (interface{}, error) {
	ret := _m.Called(ctx)

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PubSub_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type PubSub_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PubSub_Expecter) Receive(ctx interface{}) *PubSub_Receive_Call {
	return &PubSub_Receive_Call{Call: _e.mock.On("Receive", ctx)}
}

func (_c *PubSub_Receive_Call) Run(run func(ctx context.Context)) *PubSub_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PubSub_Receive_Call) Return(_a0 interface{}, _a1 error) *PubSub_Receive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PubSub_Receive_Call) RunAndReturn(run func(context.Context) (interface{}, error)) *PubSub_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, channels
func (_m *PubSub) Subscribe(ctx context.Context, channels ...string) error {
	_va := make([]interface{}, len(channels))
	for _i := range channels {
		_va[_i] = channels[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, channels...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PubSub_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type PubSub_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - channels ...string
func (_e *PubSub_Expecter) Subscribe(ctx interface{}, channels ...interface{}) *PubSub_Subscribe_Call {
	return &PubSub_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{ctx}, channels...)...)}
}

func (_c *PubSub_Subscribe_Call) Run(run func(ctx context.Context, channels ...string)) *PubSub_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *PubSub_Subscribe_Call) Return(_a0 error) *PubSub_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PubSub_Subscribe_Call) RunAndReturn(run func(context.Context, ...string) error) *PubSub_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with given fields: ctx, channels
func (_m *PubSub) Unsubscribe(ctx context.Context, channels ...string) error {
	_va := make([]interface{}, len(channels))
	for _i := range channels {
		_va[_i] = channels[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = rf(ctx, channels...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PubSub_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type PubSub_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - channels ...string
func (_e *PubSub_Expecter) Unsubscribe(ctx interface{}, channels ...interface{}) *PubSub_Unsubscribe_Call {
	return &PubSub_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe",
		append([]interface{}{ctx}, channels...)...)}
}

func (_c *PubSub_Unsubscribe_Call) Run(run func(ctx context.Context, channels ...string)) *PubSub_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *PubSub_Unsubscribe_Call) Return(_a0 error) *PubSub_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PubSub_Unsubscribe_Call) RunAndReturn(run func(context.Context, ...string) error) *PubSub_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewPubSub interface {
	mock.TestingT
	Cleanup(func())
}

// NewPubSub creates a new instance of PubSub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPubSub(t mockConstructorTestingTNewPubSub) *PubSub {
	mock := &PubSub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
