// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	redis "github.com/redis/go-redis/v9"
)

// RedisClient is an autogenerated mock type for the RedisClient type
type RedisClient struct {
	mock.Mock
}

type RedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RedisClient) EXPECT() *RedisClient_Expecter {
	return &RedisClient_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: ctx, keys
func (_m *RedisClient) Del(ctx context.Context, keys ...string) *redis.IntCmd {
	_va := make([]interface{}, len(keys))
	for _i := range keys {
		_va[_i] = keys[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *redis.IntCmd
	if rf, ok := ret.Get(0).(func(context.Context, ...string) *redis.IntCmd); ok {
		r0 = rf(ctx, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.IntCmd)
		}
	}

	return r0
}

// RedisClient_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type RedisClient_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *RedisClient_Expecter) Del(ctx interface{}, keys ...interface{}) *RedisClient_Del_Call {
	return &RedisClient_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *RedisClient_Del_Call) Run(run func(ctx context.Context, keys ...string)) *RedisClient_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *RedisClient_Del_Call) Return(_a0 *redis.IntCmd) *RedisClient_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RedisClient_Del_Call) RunAndReturn(run func(context.Context, ...string) *redis.IntCmd) *RedisClient_Del_Call {
	_c.Call.Return(run)
	return _c
}

// HGetAll provides a mock function with given fields: ctx, key
func (_m *RedisClient) HGetAll(ctx context.Context, key string) *redis.MapStringStringCmd {
	ret := _m.Called(ctx, key)

	var r0 *redis.MapStringStringCmd
	if rf, ok := ret.Get(0).(func(context.Context, string) *redis.MapStringStringCmd); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.MapStringStringCmd)
		}
	}

	return r0
}

// RedisClient_HGetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HGetAll'
type RedisClient_HGetAll_Call struct {
	*mock.Call
}

// HGetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *RedisClient_Expecter) HGetAll(ctx interface{}, key interface{}) *RedisClient_HGetAll_Call {
	return &RedisClient_HGetAll_Call{Call: _e.mock.On("HGetAll", ctx, key)}
}

func (_c *RedisClient_HGetAll_Call) Run(run func(ctx context.Context, key string)) *RedisClient_HGetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RedisClient_HGetAll_Call) Return(_a0 *redis.MapStringStringCmd) *RedisClient_HGetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RedisClient_HGetAll_Call) RunAndReturn(run func(context.Context, string) *redis.MapStringStringCmd) *RedisClient_HGetAll_Call {
	_c.Call.Return(run)
	return _c
}

// HSet provides a mock function with given fields: ctx, key, values
func (_m *RedisClient) HSet(ctx context.Context, key string, values ...interface{}) *redis.IntCmd {
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, values...)
	ret := _m.Called(_ca...)

	var r0 *redis.IntCmd
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *redis.IntCmd); ok {
		r0 = rf(ctx, key, values...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.IntCmd)
		}
	}

	return r0
}

// RedisClient_HSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HSet'
type RedisClient_HSet_Call struct {
	*mock.Call
}

// HSet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - values ...interface{}
func (_e *RedisClient_Expecter) HSet(ctx interface{}, key interface{}, values ...interface{}) *RedisClient_HSet_Call {
	return &RedisClient_HSet_Call{Call: _e.mock.On("HSet",
		append([]interface{}{ctx, key}, values...)...)}
}

func (_c *RedisClient_HSet_Call) Run(run func(ctx context.Context, key string, values ...interface{})) *RedisClient_HSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *RedisClient_HSet_Call) Return(_a0 *redis.IntCmd) *RedisClient_HSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RedisClient_HSet_Call) RunAndReturn(run func(context.Context, string, ...interface{}) *redis.IntCmd) *RedisClient_HSet_Call {
	_c.Call.Return(run)
	return _c
}

// NewRedisClient creates a new instance of RedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisClient {
	mock := &RedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
