# Tests and publishes the JS client to npm

name: Test & Publish JS Client

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - working-directory: clients/js
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm ci
          npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - working-directory: clients/js
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: |
          npm version ${{ github.ref_name }}
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
